# 1. LECTURA CSV RELACIONES/ENTIDADES

In [4]:
import pandas as pd

In [114]:
entis = pd.read_csv("C:/Users/andre/OneDrive/Escritorio/TFM/KAG/AI-KG/Project/KAG-Graph-over-AI-KG/data/processed/csv/1000_rels_entis_subset.csv")

In [72]:
entis.head(2)

,entidades,rels,id,hlight_b
0,"('information_overload', 'recommendation_system')","['methodUsedBy', 'usesMethod']",arXiv:0709.2562,Recommender|systems|Recommender|systems|inform...
1,"('recommendation_method', 'recommender_system')","['usesMethod', 'methodUsedBy']",arXiv:0709.2562,Recommender|systems|method|recommending|method...

In [105]:
entis['entidades'].str.replace("(", "").str.replace(")", "").str.replace("'", "").str.split(',')

0           [information_overload,  recommendation_system]
1             [recommendation_method,  recommender_system]
2         [collaborative_filtering,  information_overload]
3           [collaborative_filtering,  recommender_system]
4                             [database,  database_system]
                               ...
59139                                 [adaboost,  bagging]
59140                          [linearization,  statistic]
59141                    [data_set,  statistical_analysis]
59142    [neural_network,  radial_basis_function_neural...
59143          [adaptive_network,  distributed_estimation]
Name: entidades, Length: 59144, dtype: object

## ENTIDADES --> LISTA DE TUPLAS --> SET DE ENTIDADES

In [106]:
# entis.groupby("id")[['entidades', 'hlight_b']].agg(' '.join)
entis['entidades_lst'] = entis['entidades'].str.replace("(", "").str.replace(")", "").str.replace("'", "").str.split(',')

In [107]:
entis.groupby("id")['entidades_lst'].agg(lambda x: set(sum(x, [])))

id
arXiv:0709.2562          {prediction_quality, information_system,  reco...
arXiv:0712.1845          {recognition,  segmentation_algorithm, machine...
arXiv:0801.0887          {semantics,  theoretical_model, semantic_repre...
arXiv:0802.3748          {recommendation,  embedded_system, simulation,...
arXiv:0803.4092          {adaboost,  boosting_algorithm,  margin, class...
                                               ...
arXiv:cs/0607110         {adaboost,  boosting_algorithm, classifier,  n...
arXiv:cs/0703042         { matchmaking_service,  recommendation_system,...
arXiv:cs/9701102         {semantics, semantic_representation,  learning...
arXiv:math/0508276       {base_learner, machine_learning, linear_regres...
arXiv:physics/0507143    {dependency_test,  bagging, adaptive_algorithm...
Name: entidades_lst, Length: 1000, dtype: object

In [93]:
print(type(entis['entidades'].iloc[0]))

<class 'str'>

## PALABRAS ENCONTRADAS (hlight_b) --> SET

In [74]:
entis['hlight_b'] = entis['hlight_b'].astype(str).str.split('|')

In [75]:
entis['hlight_b'][0]

['Recommender', 'systems', 'Recommender', 'systems', 'information', 'systems']

In [76]:
entis['hlight_b'] = entis['hlight_b'].apply(lambda x: [s.lower() for s in x])

In [77]:
# entis.groupby("id")['hlight_b'].agg(';'.join)
# entis.groupby("id")['hlight_b'].set(sum())
# entis.groupby("id")['hlight_b'].agg(lambda x: list(set(sum(x, []))))[0]
entis.groupby("id")['hlight_b'].agg(lambda x: set(sum(x, [])))[0]

C:\Users\andre\AppData\Local\Temp\ipykernel_15408\3476585072.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  entis.groupby("id")['hlight_b'].agg(lambda x: set(sum(x, [])))[0]

{'algorithm',
 'collaborative',
 'correlations',
 'data',
 'databases',
 'distribution',
 'filtering',
 'information',
 'internet',
 'method',
 'methods',
 'needed',
 'overload',
 'predictions',
 'quality',
 'recommender',
 'recommending',
 'simulations',
 'statistical',
 'systems',
 'test',
 'tests',
 'user'}

In [73]:
entis.dtypes

entidades    object
rels         object
id           object
hlight_b     object
dtype: object

In [78]:
entis2 = entis.groupby("id", as_index=False).agg({
    "entidades": list,
    "hlight_b": lambda x: set(sum(x, []))
})

In [108]:
entis2["entidades"][0]

["('information_overload', 'recommendation_system')",
 "('recommendation_method', 'recommender_system')",
 "('collaborative_filtering', 'information_overload')",
 "('collaborative_filtering', 'recommender_system')",
 "('database', 'database_system')",
 "('database_system', 'information_system')",
 "('collaborative_filtering', 'recommendation_method')",
 "('database', 'user_information')",
 "('collaborative_filtering', 'recommendation_system')",
 "('database', 'internet')",
 "('statistical_method', 't_test')",
 "('prediction_quality', 'recommender_system')",
 "('recommendation_method', 'recommendation_system')",
 "('database_system', 'system_r')",
 "('recommendation', 'recommender_system')",
 "('collaborative_filtering_algorithm', 'recommender_system')",
 "('correlation', 'statistical_method')",
 "('information_overload', 'recommender_system')",
 "('collaborative_filtering', 'user_information')",
 "('filter', 'information_need')",
 "('collaborative_filtering_system', 'information_overload')",
 "('collaborative_filtering', 'recommendation')",
 "('simulation', 'simulator')",
 "('filter', 'filtering')",
 "('collaborative_filtering', 'recommenders')",
 "('distributed_data', 'internet')",
 "('database', 'statistic')",
 "('information_system', 'internet')",
 "('database', 'information_system')",
 "('e', 'statistical_test')"]

In [80]:
entis2["hlight_b"][0]

{'algorithm',
 'collaborative',
 'correlations',
 'data',
 'databases',
 'distribution',
 'filtering',
 'information',
 'internet',
 'method',
 'methods',
 'needed',
 'overload',
 'predictions',
 'quality',
 'recommender',
 'recommending',
 'simulations',
 'statistical',
 'systems',
 'test',
 'tests',
 'user'}

In [65]:
entis2.head(10)

,id,entidades,hlight_b
0,arXiv:0709.2562,"[('information_overload', 'recommendation_syst...",NaN
1,arXiv:0712.1845,"[('recognition', 'statistical_method'), ('imag...",NaN
2,arXiv:0801.0887,"[('semantics', 'structure'), ('semantic_inform...",NaN
3,arXiv:0802.3748,"[('recommendation_method', 'recommender_system...",NaN
4,arXiv:0803.4092,"[('similarity', 'similarity_function'), ('adab...",NaN
5,arXiv:0807.2900,"[('principal_components_analysis', 'statistica...",NaN
6,arXiv:0810.4553,"[('boosting', 'weighting'), ('adaboost_algorit...",NaN
7,arXiv:0811.0416,"[('classification_process', 'classifier'), ('c...",NaN
8,arXiv:0812.0759,"[('fusion', 'object_recognition'), ('feature_e...",NaN
9,arXiv:0901.2266,"[('pca', 'reduced_principal_component'), ('pca...",NaN

#  COMPARACION ENTIDADES ENCONTRADAS CON ENTIDADES BASE

In [135]:
entis = pd.read_csv("C:/Users/andre/OneDrive/Escritorio/TFM/KAG/AI-KG/Project/KAG-Graph-over-AI-KG/data/processed/csv/1000_rels_entis_subset.csv")

In [136]:
resultados = pd.read_csv("C:/Users/andre/OneDrive/Escritorio/TFM/KAG/AI-KG/Project/KAG-Graph-over-AI-KG/outputs/resultados/OUTPUT_2026-04-22_01-56.csv")

In [137]:
# entis.groupby("id")[['entidades', 'hlight_b']].agg(' '.join)
entis['entidades_lst'] = entis['entidades'].str.replace("(", "").str.replace(")", "").str.replace("'", "").str.split(',')
entis['entidades_lst'] = entis['entidades_lst'].apply(lambda x: [s.strip() for s in x])

entis = entis.groupby("id", as_index=False)['entidades_lst'].agg(lambda x: set(sum(x, [])))

In [138]:
entis.loc[entis["id"] == "arXiv:0709.2562", 'entidades_lst'].values[0]

{'collaborative_filtering',
 'collaborative_filtering_algorithm',
 'collaborative_filtering_system',
 'correlation',
 'database',
 'database_system',
 'distributed_data',
 'e',
 'filter',
 'filtering',
 'information_need',
 'information_overload',
 'information_system',
 'internet',
 'prediction_quality',
 'recommendation',
 'recommendation_method',
 'recommendation_system',
 'recommender_system',
 'recommenders',
 'simulation',
 'simulator',
 'statistic',
 'statistical_method',
 'statistical_test',
 'system_r',
 't_test',
 'user_information'}

In [139]:
resultados['entidades'] = resultados['entidades'].astype(str).str.split(';')
resultados['entidades'] = resultados['entidades'].apply(lambda x: [s.lower() for s in x])

In [140]:
resultados['entidades'] = resultados['entidades'].apply(
    lambda s: {elem.strip().replace(' ', '_') for elem in s}
)

In [141]:
resultados['entidades'] = resultados['entidades'].apply(
    set
)

In [142]:
entis

                        id                                      entidades_lst
0          arXiv:0709.2562  {information_system, database, information_nee...
1          arXiv:0712.1845  {object_recognition, fast_recognition, neural_...
2          arXiv:0801.0887  {knowledge_based_system, information_system, n...
3          arXiv:0802.3748  {data_set, recommendation_system, generation_m...
4          arXiv:0803.4092  {similarity_function, classifier, function, cl...
..                     ...                                                ...
995       arXiv:cs/0607110  {classifier, recursion, classifying, weak_lear...
996       arXiv:cs/0703042  {collaborative_filtering__cf__algorithm, user_...
997       arXiv:cs/9701102  {knowledge_based_system, data_processing_syste...
998     arXiv:math/0508276  {optimization_technique, optimization_problem,...
999  arXiv:physics/0507143  {neural_network, correlation_analysis, adaptiv...

[1000 rows x 2 columns]

In [143]:
resultados

,csv_source,id,entidades
0,1000_abs_subset,arXiv:0709.2562,"{internet, information_overload, movielens_dat..."
1,1000_abs_subset,arXiv:0712.1845,"{neuron, error_rate, rhesus_monkey_brain_tissu..."
2,1000_abs_subset,arXiv:0801.0887,"{knowledge_discovery, scale-free_graph, inform..."
3,1000_abs_subset,arXiv:0802.3748,"{benchmark_data_set, converges_fast, standard_..."
4,1000_abs_subset,arXiv:0803.4092,"{arc-gv_algorithm, maximum_margin_solution, bo..."

In [144]:
pred = {'pajaro', 'animal', 'cebolla'}
true = {'pajaro', 'animal'}

In [145]:
pred & true

{'animal', 'pajaro'}

In [146]:
pred - true

{'cebolla'}

In [147]:
true - pred

set()

In [5]:
def precision_recall_f1(pred, true):
    pred = set(pred)
    true = set(true)
    comunes = pred & true
    solo_pred = pred - true
    solo_true = true - pred

    tp = len(comunes)
    fp = len(solo_pred)
    fn = len(solo_true)

    precision = tp / (tp + fp) if (tp + fp) > 0 else 0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0

    if precision + recall == 0:
        f1 = 0
    else:
        f1 = 2 * precision * recall / (precision + recall)

    return precision, recall, f1, list(comunes), list(solo_pred), list(solo_true)

In [8]:
precision_recall_f1(['pajaro', 'animal', 'cebolla'], ['pajaro', 'animal'])

(0.6666666666666666, 1.0, 0.8, ['pajaro', 'animal'], ['cebolla'], [])

In [150]:
[precision, recall, f1, comunes, solo_pred, solo_true] = precision_recall_f1(resultados['entidades'][0], entis['entidades_lst'][0])

In [9]:
def metricas_entidades(resultados, entis, df_metricas):
    
    """Calculo de metricas de entidades"""
    resultados['entidades'] = resultados['entidades'].astype(str).str.split(';')
    resultados['entidades'] = resultados['entidades'].apply(lambda x: [s.lower() for s in x])
    resultados['entidades'] = resultados['entidades'].apply(lambda s: {elem.strip().replace(' ', '_') for elem in s})
    # resultados['entidades'] = resultados['entidades'].apply(set)
    
    
    entis['entidades_lst'] = entis['entidades'].str.replace("(", "").str.replace(")", "").str.replace("'", "").str.split(',')
    entis['entidades_lst'] = entis['entidades_lst'].apply(lambda x: [s.strip() for s in x])
    # entis = entis.groupby("id", as_index=False)['entidades_lst'].agg(lambda x: set(sum(x, [])))
    entis = entis.groupby("id", as_index=False)['entidades_lst'].agg(lambda x: sum(x, []))

    # Respuestas con formato valido
    for i, row in resultados.iterrows():
        id = row["id"]
        pred = row["entidades"]
        true = entis.loc[entis["id"] == id, 'entidades_lst'].values[0]
        precision, recall, f1, comunes, solo_pred, solo_true = precision_recall_f1(pred, true)
        # df_metricas.loc[df_metricas["id"] == id, ["precision", "recall", "f1", "comunes", "solo_pred", "solo_true"]] = [precision, recall, f1, comunes, solo_pred, solo_true]
        # df_metricas.loc[df_metricas["id"] == id, ["precision", "recall", "f1", "comunes", "solo_pred", "solo_true"]] = [precision, recall, f1, list(comunes), list(solo_pred), list(solo_true)]
        metricas = {
            "precision": precision,
            "recall": recall,
            "f1": f1,
            "comunes": str(comunes),
            "solo_pred": str(solo_pred),
            "solo_true": str(solo_true)
        }
        for col, val in metricas.items():
            df_metricas.loc[df_metricas["id"] == id, col] = val
        # idx = df_metricas.index[df_metricas["id"] == id][0]

    return df_metricas

In [10]:
entis = pd.read_csv("C:/Users/andre/OneDrive/Escritorio/TFM/KAG/AI-KG/Project/KAG-Graph-over-AI-KG/data/processed/csv/1000_rels_entis_subset.csv")

In [11]:
resultados = pd.read_csv("C:/Users/andre/OneDrive/Escritorio/TFM/KAG/AI-KG/Project/KAG-Graph-over-AI-KG/outputs/resultados/OUTPUT_2026-04-22_01-56.csv")

In [12]:
df_metricas = pd.DataFrame()

In [13]:
df_metricas["id"] = resultados['id']

In [14]:
df_metricas_2 = metricas_entidades(resultados, entis, df_metricas)

In [15]:
df_metricas_2

,id,precision,recall,f1,comunes,solo_pred,solo_true
0,arXiv:0709.2562,0.181818,0.071429,0.102564,"['information_overload', 'internet']",['correlation-based_collaborative_filtering_al...,"['correlation', 'database_system', 'recommenda..."
1,arXiv:0712.1845,0.285714,0.070175,0.112676,"['computational_efficiency', 'neuron', 'artifi...","['anra', 'rhesus_monkey_brain_tissue', 'identi...","['statistical_analysis', 'variable', 'q_learni..."
2,arXiv:0801.0887,0.083333,0.027778,0.041667,['information_retrieval'],"['amplifier_effect', 'power-law_appearance', '...","['knowledge_graph', 'semantic_representation',..."
3,arXiv:0802.3748,0.000000,0.000000,0.000000,[],"['world_of_information', 'numerical_simulation...","['filter', 'similarity', 'simulator', 'generat..."
4,arXiv:0803.4092,0.000000,0.000000,0.000000,[],"[""adaboost's_convergence_properties"", 'arc-gv_...","['similarity', 'adaboost_algorithm', 'boosting..."

In [205]:
lst=[1,2,5]
id = "arXiv:0709.2562"

In [207]:
df_metricas.loc[df_metricas["id"] == id, 'comunes'] = [lst]

ValueError: Must have equal len keys and value when setting with an ndarray

In [209]:
df_metricas.at[0, 'listas_col'] = str([10, 20, 30])

C:\Users\andre\AppData\Local\Temp\ipykernel_17060\3767089881.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[10, 20, 30]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df_metricas.at[0, 'listas_col'] = str([10, 20, 30])

In [210]:
df_metricas

                id  precision    recall        f1 comunes    listas_col
0  arXiv:0709.2562   0.181818  0.071429  0.102564     nan  [10, 20, 30]
1  arXiv:0712.1845        NaN       NaN       NaN     nan           NaN
2  arXiv:0801.0887        NaN       NaN       NaN     nan           NaN
3  arXiv:0802.3748        NaN       NaN       NaN     nan           NaN
4  arXiv:0803.4092        NaN       NaN       NaN     nan           NaN

In [ ]:
df_metricas.at[idx, col] = val