# 0. INICIALIZACION

In [4]:
import pandas as pd

# COMPROBACION DE DUPLICADOS

Sí hay duplicados.  Al estar separados por entidades y relaciones los archivos aparecen varias veces.

En el archivo res1:
- 1217610 registros
- 537320 ids NO duplicados
- 241893 ids CON DUPLICADOS

In [6]:
path = "C:/Users/andre/OneDrive/Escritorio/TFM/KAG/AI-KG/AI-KG Dataset/DATA/"
file = f"{path}res1.csv"

In [7]:
df = pd.read_csv(file, usecols=['text_id'])

Nº DE REGISTROS

In [20]:
df.count()

text_id    1217610
dtype: int64

Nº DE NO DUPLICADOS

In [19]:
df[~df.duplicated()].count()

text_id    537320
dtype: int64

Nº DE REGISTROS CON ALGUN DUPLICADO

In [23]:
df[df.duplicated(keep=False)].sort_values(by="text_id")

                        text_id
389593          arXiv:0704.0009
959845          arXiv:0704.0009
329074          arXiv:0704.0009
18694           arXiv:0704.0042
57487           arXiv:0704.0042
...                         ...
1101971  arXiv:solv-int/9810001
9510     arXiv:solv-int/9810001
688446   arXiv:solv-int/9810001
683951   arXiv:solv-int/9906003
1020802  arXiv:solv-int/9906003

[922183 rows x 1 columns]

Nº REGISTROS DUPLICADOS

In [26]:
df[df.duplicated()].drop_duplicates().count()

text_id    241893
dtype: int64

In [32]:
df[df["text_id"] == "arXiv:1711.00789"]

,relaciones,text_id,hlight_b,dup_id
94101,includesMaterial|materialIncludedBy,arXiv:1711.00789,images|data|dimensional|images|data,1
255580,broader|narrower,arXiv:1711.00789,grids|framework|computational,2
391940,usesMethod|methodUsedBy,arXiv:1711.00789,discrete|wavelet|transforms|wavelet|transforms,3
636194,methodUsedBy|usesMethod,arXiv:1711.00789,modeling|model|inference,4
662143,OtherEntityIncludedBy|includesOtherEntity,arXiv:1711.00789,images|range|image|images,5
732636,includesMaterial|materialIncludedBy,arXiv:1711.00789,modeling|model|database,6
905033,usesOtherEntity|otherEntityUsedBy,arXiv:1711.00789,learning|computational|learning,7
954283,OtherEntityIncludedBy|includesOtherEntity,arXiv:1711.00789,images|data|images|resolution|image,8
1134499,methodUsedBy|usesMethod,arXiv:1711.00789,algorithm|inference,9
1217606,methodUsedBy|usesMethod,arXiv:1711.00789,methods|discrete|Bayesian,10

# ELIMINACION DE DUPLICADOS

Eliminar duplicados poniendo la info de relaciones y entidades como nuevas columnas del primer registro

In [47]:
path = "C:/Users/andre/OneDrive/Escritorio/TFM/KAG/AI-KG/AI-KG Dataset/DATA/"
file = f"{path}res1.csv"

In [48]:
df = pd.read_csv(file, usecols=['text_id', 'relaciones', 'hlight_b'])

In [49]:
df

,relaciones,text_id,hlight_b
0,supportsOtherEntity|methodUsedBy|usesMethod|Ot...,arXiv:1408.6930,information|overload|Recommender|systems|infor...
1,supportsOtherEntity|methodUsedBy|usesMethod|Ot...,arXiv:2202.06248,information|overload|Recommendation|Systems|in...
2,supportsOtherEntity|methodUsedBy|usesMethod|Ot...,arXiv:2011.02260,information|recommender|systems|recommender|sy...
3,supportsOtherEntity|methodUsedBy|usesMethod|Ot...,arXiv:1703.09108,recommender|systems|systems|information|overlo...
4,supportsOtherEntity|methodUsedBy|usesMethod|Ot...,arXiv:1303.6369,Information|overload|information|recommender|s...
...,...,...,...
1217605,methodUsedBy|usesMethod,arXiv:1212.2467,discrete|grid|discrete|Bayesian|methods
1217606,methodUsedBy|usesMethod,arXiv:1711.00789,methods|discrete|Bayesian
1217607,methodUsedBy|usesMethod,arXiv:2002.03355,discrete|grid|inference|methods
1217608,methodUsedBy|usesMethod,arXiv:1701.01634,Bayesian|grid|discretization|discrete
1217609,methodUsedBy|usesMethod,arXiv:1903.11940,method|method|discrete

In [50]:
df["dup_id"] = df.groupby("text_id").cumcount() + 1

In [51]:
df[df["text_id"] == "arXiv:1711.00789"]

,relaciones,text_id,hlight_b,dup_id
94101,includesMaterial|materialIncludedBy,arXiv:1711.00789,images|data|dimensional|images|data,1
255580,broader|narrower,arXiv:1711.00789,grids|framework|computational,2
391940,usesMethod|methodUsedBy,arXiv:1711.00789,discrete|wavelet|transforms|wavelet|transforms,3
636194,methodUsedBy|usesMethod,arXiv:1711.00789,modeling|model|inference,4
662143,OtherEntityIncludedBy|includesOtherEntity,arXiv:1711.00789,images|range|image|images,5
732636,includesMaterial|materialIncludedBy,arXiv:1711.00789,modeling|model|database,6
905033,usesOtherEntity|otherEntityUsedBy,arXiv:1711.00789,learning|computational|learning,7
954283,OtherEntityIncludedBy|includesOtherEntity,arXiv:1711.00789,images|data|images|resolution|image,8
1134499,methodUsedBy|usesMethod,arXiv:1711.00789,algorithm|inference,9
1217606,methodUsedBy|usesMethod,arXiv:1711.00789,methods|discrete|Bayesian,10

In [36]:
# Pivotear: convertir filas duplicadas en columnas
df_pivot = df.pivot(index="text_id", columns="dup_id")

In [37]:
df_pivot

                                               relaciones  \
dup_id                                                 1
text_id
arXiv:0704.0009                   methodUsedBy|usesMethod
arXiv:0704.0012         otherEntityUsedBy|usesOtherEntity
arXiv:0704.0041         OtherEntityUsedBy|usesOtherEntity
arXiv:0704.0042                          narrower|broader
arXiv:0704.0047         methodEvaluatedBy|evaluatesMethod
...                                                   ...
arXiv:solv-int/9912015  usesOtherEntity|OtherEntityUsedBy
arXiv:supr-con/9506002                   broader|narrower
arXiv:supr-con/9506003                   broader|narrower
arXiv:supr-con/9608001  usesOtherEntity|OtherEntityUsedBy
arXiv:supr-con/9608007                   broader|narrower

                                                           \
dup_id                                                 2
text_id
arXiv:0704.0009         otherEntityUsedBy|usesOtherEntity
arXiv:0704.0012                                       NaN
arXiv:0704.0041                                       NaN
arXiv:0704.0042                   methodUsedBy|usesMethod
arXiv:0704.0047                   methodUsedBy|usesMethod
...                                                   ...
arXiv:solv-int/9912015                                NaN
arXiv:supr-con/9506002                                NaN
arXiv:supr-con/9506003                                NaN
arXiv:supr-con/9608001                                NaN
arXiv:supr-con/9608007                                NaN

                                                                           \
dup_id                                                                 3
text_id
arXiv:0704.0009                                   methodUsedBy|usesMethod
arXiv:0704.0012                                                       NaN
arXiv:0704.0041                                                       NaN
arXiv:0704.0042         usesMethod|OtherEntityIncludedBy|methodUsedBy|...
arXiv:0704.0047                                                       NaN
...                                                                   ...
arXiv:solv-int/9912015                                                NaN
arXiv:supr-con/9506002                                                NaN
arXiv:supr-con/9506003                                                NaN
arXiv:supr-con/9608001                                                NaN
arXiv:supr-con/9608007                                                NaN

                                                                           \
dup_id                                                                 4
text_id
arXiv:0704.0009                                                       NaN
arXiv:0704.0012                                                       NaN
arXiv:0704.0041                                                       NaN
arXiv:0704.0042         includesOtherEntity|usesOtherEntity|OtherEntit...
arXiv:0704.0047                                                       NaN
...                                                                   ...
arXiv:solv-int/9912015                                                NaN
arXiv:supr-con/9506002                                                NaN
arXiv:supr-con/9506003                                                NaN
arXiv:supr-con/9608001                                                NaN
arXiv:supr-con/9608007                                                NaN

                                                      ... hlight_b            \
dup_id                   5    6    7    8    9    10  ...       57   58   59
text_id                                               ...
arXiv:0704.0009         NaN  NaN  NaN  NaN  NaN  NaN  ...      NaN  NaN  NaN
arXiv:0704.0012         NaN  NaN  NaN  NaN  NaN  NaN  ...      NaN  NaN  NaN
arXiv:0704.0041         NaN  NaN  NaN  NaN  NaN  NaN  ...      NaN  NaN  NaN
arXiv:0704.0042         NaN  NaN  NaN  NaN  NaN  NaN  ...      NaN  NaN  NaN
arXiv:0704.0047         NaN  NaN  NaN  NaN  NaN  NaN  ...      NaN  NaN  NaN
...                     ...  ...  ...  ...  ...  ...  ...      ...  ...  ...
arXiv:solv-int/9912015  NaN  NaN  NaN  NaN  NaN  NaN  ...      NaN  NaN  NaN
arXiv:supr-con/9506002  NaN  NaN  NaN  NaN  NaN  NaN  ...      NaN  NaN  NaN
arXiv:supr-con/9506003  NaN  NaN  NaN  NaN  NaN  NaN  ...      NaN  NaN  NaN
arXiv:supr-con/9608001  NaN  NaN  NaN  NaN  NaN  NaN  ...      NaN  NaN  NaN
arXiv:supr-con/9608007  NaN  NaN  NaN  NaN  NaN  NaN  ...      NaN  NaN  NaN


dup_id                   60   61   62   63   64   65   66
text_id
arXiv:0704.0009         NaN  NaN  NaN  NaN  NaN  NaN  NaN
arXiv:0704.0012         NaN  NaN  NaN  NaN  NaN  NaN  NaN
arXiv:0704.0041         NaN  NaN  NaN  NaN  NaN  NaN  NaN
arXiv:0704.0042         NaN  NaN  NaN  NaN  NaN  NaN  NaN
arXiv:0704.0047         NaN  NaN  NaN  NaN  NaN  NaN  NaN
...                     ...  ...  ...  ...  ...  ...  ...
arXiv:solv-int/9912015  NaN  NaN  NaN  NaN  NaN  NaN  NaN
arXiv:supr-con/9506002  NaN  NaN  NaN  NaN  NaN  NaN  NaN
arXiv:supr-con/9506003  NaN  NaN  NaN  NaN  NaN  NaN  NaN
arXiv:supr-con/9608001  NaN  NaN  NaN  NaN  NaN  NaN  NaN
arXiv:supr-con/9608007  NaN  NaN  NaN  NaN  NaN  NaN  NaN

[537320 rows x 132 columns]

In [ ]:

# Aplanar nombres de columnas
df_pivot.columns = [
    f"{col[0]}" if col[1] == 1 else f"{col[0]}_{col[1]}"
    for col in df_pivot.columns
]

# Resetear índice para volver a tener ID como columna
df_final = df_pivot.reset_index()

In [53]:
df_final

,text_id,relaciones,relaciones_2,relaciones_3,relaciones_4,relaciones_5,relaciones_6,relaciones_7,relaciones_8,relaciones_9,...,hlight_b_57,hlight_b_58,hlight_b_59,hlight_b_60,hlight_b_61,hlight_b_62,hlight_b_63,hlight_b_64,hlight_b_65,hlight_b_66
0,arXiv:0704.0009,methodUsedBy|usesMethod,otherEntityUsedBy|usesOtherEntity,methodUsedBy|usesMethod,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,arXiv:0704.0012,otherEntityUsedBy|usesOtherEntity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,arXiv:0704.0041,OtherEntityUsedBy|usesOtherEntity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,arXiv:0704.0042,narrower|broader,methodUsedBy|usesMethod,usesMethod|OtherEntityIncludedBy|methodUsedBy|...,includesOtherEntity|usesOtherEntity|OtherEntit...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,arXiv:0704.0047,methodEvaluatedBy|evaluatesMethod,methodUsedBy|usesMethod,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537315,arXiv:solv-int/9912015,usesOtherEntity|OtherEntityUsedBy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
537316,arXiv:supr-con/9506002,broader|narrower,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
537317,arXiv:supr-con/9506003,broader|narrower,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
537318,arXiv:supr-con/9608001,usesOtherEntity|OtherEntityUsedBy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
537319,arXiv:supr-con/9608007,broader|narrower,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [55]:
df_final[df_final.duplicated()]

Empty DataFrame
Columns: [text_id, relaciones, relaciones_2, relaciones_3, relaciones_4, relaciones_5, relaciones_6, relaciones_7, relaciones_8, relaciones_9, relaciones_10, relaciones_11, relaciones_12, relaciones_13, relaciones_14, relaciones_15, relaciones_16, relaciones_17, relaciones_18, relaciones_19, relaciones_20, relaciones_21, relaciones_22, relaciones_23, relaciones_24, relaciones_25, relaciones_26, relaciones_27, relaciones_28, relaciones_29, relaciones_30, relaciones_31, relaciones_32, relaciones_33, relaciones_34, relaciones_35, relaciones_36, relaciones_37, relaciones_38, relaciones_39, relaciones_40, relaciones_41, relaciones_42, relaciones_43, relaciones_44, relaciones_45, relaciones_46, relaciones_47, relaciones_48, relaciones_49, relaciones_50, relaciones_51, relaciones_52, relaciones_53, relaciones_54, relaciones_55, relaciones_56, relaciones_57, relaciones_58, relaciones_59, relaciones_60, relaciones_61, relaciones_62, relaciones_63, relaciones_64, relaciones_65, relaciones_66, hlight_b, hlight_b_2, hlight_b_3, hlight_b_4, hlight_b_5, hlight_b_6, hlight_b_7, hlight_b_8, hlight_b_9, hlight_b_10, hlight_b_11, hlight_b_12, hlight_b_13, hlight_b_14, hlight_b_15, hlight_b_16, hlight_b_17, hlight_b_18, hlight_b_19, hlight_b_20, hlight_b_21, hlight_b_22, hlight_b_23, hlight_b_24, hlight_b_25, hlight_b_26, hlight_b_27, hlight_b_28, hlight_b_29, hlight_b_30, hlight_b_31, hlight_b_32, hlight_b_33, ...]
Index: []

[0 rows x 133 columns]

In [54]:
path = "C:/Users/andre/OneDrive/Escritorio/TFM/KAG/AI-KG/AI-KG Dataset/DATA/"
out_file = f"{path}res1_group.csv"

df_final.to_csv(out_file, index=False)

In [40]:
df_final.columns

Index(['text_id', 'relaciones', 'relaciones_2', 'relaciones_3', 'relaciones_4',
       'relaciones_5', 'relaciones_6', 'relaciones_7', 'relaciones_8',
       'relaciones_9',
       ...
       'hlight_b_57', 'hlight_b_58', 'hlight_b_59', 'hlight_b_60',
       'hlight_b_61', 'hlight_b_62', 'hlight_b_63', 'hlight_b_64',
       'hlight_b_65', 'hlight_b_66'],
      dtype='object', length=133)

In [41]:
df_final[~df_final["hlight_b_66"].isna()]

,text_id,relaciones,relaciones_2,relaciones_3,relaciones_4,relaciones_5,relaciones_6,relaciones_7,relaciones_8,relaciones_9,...,hlight_b_57,hlight_b_58,hlight_b_59,hlight_b_60,hlight_b_61,hlight_b_62,hlight_b_63,hlight_b_64,hlight_b_65,hlight_b_66
296540,arXiv:1910.02114,methodUsedBy|usesMethod,methodUsedBy|usesMethod,usesOtherEntity|methodUsedBy|otherEntityUsedBy...,narrower|broader,usesMethod|methodUsedBy,broader|narrower,includesMaterial|materialIncludedBy,broader|methodIncludedBy|narrower|narrower|inc...,methodUsedBy|usesMethod,...,dimensionality|Principal|Component|Analysis|Pr...,machine|learning|based|support|vector|machine,learning|computational|computational,data|Analysis|image|analysis,dimensionality|reduction|vector,machine|learning|Model|support|vector|machine,machine|learning|machine|processing,feature|extraction|methods|methods|classificat...,classification|classification|accuracy|classif...,kernel|methods|Kernel

In [52]:
df[df["text_id"] == "arXiv:1910.02114"]

,relaciones,text_id,hlight_b,dup_id
953,methodUsedBy|usesMethod,arXiv:1910.02114,dimension|PCA|features,1
1666,methodUsedBy|usesMethod,arXiv:1910.02114,dimensionality|PCA,2
15712,usesOtherEntity|methodUsedBy|otherEntityUsedBy...,arXiv:1910.02114,kernel|Kernel|SVM,3
16188,narrower|broader,arXiv:1910.02114,face|image|recognition|face|tasks,4
32414,usesMethod|methodUsedBy,arXiv:1910.02114,Linear|pattern|recognition|linear,5
...,...,...,...,...
1063835,broader|narrower,arXiv:1910.02114,machine|learning|Model|support|vector|machine,62
1087812,usesMethod|methodUsedBy,arXiv:1910.02114,machine|learning|machine|processing,63
1151659,methodEvaluatedBy|evaluatesMethod,arXiv:1910.02114,feature|extraction|methods|methods|classificat...,64
1153881,methodEvaluatedBy|evaluatesMethod,arXiv:1910.02114,classification|classification|accuracy|classif...,65
1157668,broader|narrower,arXiv:1910.02114,kernel|methods|Kernel,66

In [56]:
df = pd.read_csv(file, usecols=['text_id', 'relaciones', 'hlight_b'])
path = "C:/Users/andre/OneDrive/Escritorio/TFM/KAG/AI-KG/AI-KG Dataset/DATA/"
out_file = f"{path}res1_sin_hlight_full.csv"

df.to_csv(out_file, index=False)

In [ ]:
csvs = [
    "res1",
    "res2",
    "res3",
    "res4",
    "res5-1",
    "res5-2",
    "res6-1",
    "res6-2",
    "res7-1",
    "res7-2",
    "res8-1",
    "res8-2",
    "res8-3",
    "res8-4",
        ]